// <auto-generated />
using System;
using JobForge.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobForge.Migrations
{
    [DbContext(typeof(JobForgeDbContext))]
    partial class JobForgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobForge.Audit.AuditEntry", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("EntityId").HasColumnType("uuid");
                b.Property<int>("EventType").HasColumnType("integer");
                b.Property<string>("Message").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<DateTimeOffset>("OccurredAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("UserId").HasColumnType("uuid");
                b.HasKey("Id");
                b.ToTable("AuditEntries");
            });

            modelBuilder.Entity("JobForge.Job.Job", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTimeOffset?>("CompletedAt").HasColumnType("timestamp with time zone");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("JobCode").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("JobName").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<Guid>("OwnerId").HasColumnType("uuid");
                b.Property<string>("Payload").IsRequired().HasColumnType("text");
                b.Property<int>("Priority").HasColumnType("integer");
                b.Property<DateTimeOffset?>("QueuedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Result").HasColumnType("jsonb");
                b.Property<DateTimeOffset?>("StartedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("Status").HasColumnType("integer");
                b.HasKey("Id");
                b.ToTable("Jobs");
            });

            modelBuilder.Entity("JobForge.Retry.RetryAttempt", b =>
            {
                b.Property<Guid>("JobId").HasColumnType("uuid");
                b.Property<int>("AttemptNumber").HasColumnType("integer");
                b.Property<string>("ErrorMessage").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<DateTimeOffset>("FailedAt").HasColumnType("timestamp with time zone");
                b.Property<DateTimeOffset>("NextRetryAt").HasColumnType("timestamp with time zone");
                b.HasKey("JobId", "AttemptNumber");
                b.ToTable("RetryAttempts");
            });

            modelBuilder.Entity("JobForge.Schedule.Schedule", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<bool>("IsActive").HasColumnType("boolean");
                b.Property<Guid>("JobId").HasColumnType("uuid");
                b.Property<DateTimeOffset>("RunAt").HasColumnType("timestamp with time zone");
                b.Property<int>("Type").HasColumnType("integer");
                b.HasKey("Id");
                b.ToTable("Schedules");
            });

            modelBuilder.Entity("JobForge.Users.User", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<bool>("IsActive").HasColumnType("boolean");
                b.Property<string>("NormalizedUsername").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(512).HasColumnType("character varying(512)");
                b.Property<int>("Role").HasColumnType("integer");
                b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.HasKey("Id");
                b.HasIndex("NormalizedUsername").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("JobForge.Webhooks.Webhook", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("Event").HasColumnType("integer");
                b.Property<bool>("IsActive").HasColumnType("boolean");
                b.Property<Guid>("OwnerId").HasColumnType("uuid");
                b.Property<string>("Url").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                b.HasKey("Id");
                b.ToTable("Webhooks");
            });
#pragma warning restore 612, 618
        }
    }
}